name: server
description: Custom Fedora CoreOS Server

base-image: quay.io/fedora/fedora-coreos
image-version: stable

modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
      rpm:
        - name: tailscale
          baseurl: https://pkgs.tailscale.com/stable/fedora/$releasever/$basearch
          enabled: true
          gpgcheck: true
          gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
    install:
      packages:
        - vim
        - btop
        - zsh
        - atuin
        - podlet
        - util-linux-script
        - rpmconf
        - qemu-guest-agent
        - cockpit-podman
        - cockpit-ostree
        - cockpit-selinux
        - cockpit-storaged
        - tailscale
        - starship
    remove:
      packages:
        - nano

  - type: systemd
    system:
      disabled:
        - zincati.service

  - type: signing

