name: server
description: Custom Fedora CoreOS Server

base-image: quay.io/fedora/fedora-coreos
image-version: stable

modules:
  - type: copy
    src: recipes/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo

  - type: dnf
    install:
      packages:
        - vim
        - btop
        - rpmconf
        - qemu-guest-agent
        - cockpit-podman
        - cockpit-ostree
        - cockpit-selinux
        - cockpit-storaged
        - tailscale
    remove:
      packages:
        - nano

  - type: systemd
    system:
      disabled:
        - zincati.service

  - type: signing

